services:
  db:
    image: postgres
    container_name: psql-rb
    restart: always
    environment:
      POSTGRES_DB: draughts
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"
    networks:
      - back-tier

networks:
  back-tier:
    driver: bridge
